# Generated by Django 3.2.9 on 2021-11-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='car_plate',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_chassis_no',
            field=models.CharField(max_length=30, verbose_name='رقم الشاسيه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_color',
            field=models.CharField(max_length=30, verbose_name='لون السيارة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_manufacturer',
            field=models.CharField(max_length=30, verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_model_name',
            field=models.CharField(max_length=30, verbose_name='اسم الموديل'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_model_year',
            field=models.IntegerField(verbose_name='موديل السيارة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_owner_name',
            field=models.CharField(max_length=30, verbose_name='اسم المالك'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_registration_no',
            field=models.CharField(max_length=30, verbose_name='رقم اللوحة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='منتهية'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='driver_license_number',
            field=models.CharField(max_length=30, verbose_name='رقم الرخصة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='national_identification_number',
            field=models.CharField(max_length=30, verbose_name='السجل المدني'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner_mobile_number',
            field=models.CharField(max_length=30, verbose_name='جوال المالك'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='parking_price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر اليوم'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='position_number',
            field=models.IntegerField(default=1, verbose_name='رقم حارة الركن'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation_time_per_day',
            field=models.CharField(max_length=30, verbose_name='ايام الحجز'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='اجمالي التذكرة'),
        ),
    ]
