# Generated by Django 3.2.9 on 2021-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0004_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(verbose_name='رمز رابط التذكرة'),
        ),
    ]
